#lang play
(require "base.rkt")

; test typeof:
(printf "\n---------- Test (typeof) ----------\n\n")

(test (typeof (parse 6)(mtTEnv)) (list (TNum)))
(test (typeof (num 3)(mtTEnv)) (list (TNum)))
(test (typeof (parse '{+ {+ {- 6 5} 4} 6})(mtTEnv)) 
    (list (TNum) (Cnst (TNum) (TNum)) (Cnst (TNum) (TNum)) (Cnst (TNum) (TNum)) (Cnst (TNum) (TNum)) (Cnst (TNum) (TNum)) (Cnst (TNum) (TNum))))
(test (typeof (parse '{+ 10 12})(mtTEnv)) (list (TNum) (Cnst (TNum) (TNum)) (Cnst (TNum) (TNum))))
(test (typeof (add (num 10) (num 3)) (mtTEnv)) ( list ( TNum ) ( Cnst ( TNum ) ( TNum )) ( Cnst ( TNum ) ( TNum ))))
(test (typeof (parse 'x)(anTEnv 'x (TNum) (mtTEnv))) (list (TNum)))
(reset)
(test (typeof (parse '{- 10 x}) (anTEnv 'x (TVar 1) (mtTEnv))) (list (TNum) (Cnst (TNum) (TNum)) (Cnst (TVar 1) (TNum))))
(reset)
(test (typeof (add (id 'z) (num 100)) (anTEnv 'z (TVar 1) (mtTEnv))) (list (TNum) (Cnst (TVar 1) (TNum)) (Cnst (TNum) (TNum))))
(reset)
(test/exn (typeof (fun 'x (id 'y)) (mtTEnv)) "Exception: Identificador libre = y")
(reset)
(test (typeof (fun 'x (add (id 'x) (num 1))) (mtTEnv))(list (TFun (TVar 1) (TNum)) (Cnst (TVar 1) (TNum)) (Cnst (TNum) (TNum))))
(reset)
(test (typeof (add (num 4) (app (fun 'x (add (id 'x) (num 5))) (num 10))) (mtTEnv)) 
    (list (TNum) (Cnst (TVar 1) (TNum)) (Cnst (TNum) (TNum)) (Cnst (TFun (TVar 1) (TNum)) (TFun (TNum) (TVar 2))) (Cnst (TNum) (TNum)) (Cnst (TVar 4) (TNum))))
(reset)
(test (typeof (app (fun 'x (app (fun 'y (app (fun 'z (add (add (id 'x) (id 'y)) (id 'z))) (num 3))) (num 10))) (num 5)) (mtTEnv)) (list
 (TVar 6)
 (Cnst (TVar 1) (TNum))
 (Cnst (TVar 2) (TNum))
 (Cnst (TNum) (TNum))
 (Cnst (TVar 3) (TNum))
 (Cnst (TFun (TVar 3) (TNum)) (TFun (TNum) (TVar 4)))
 (Cnst (TFun (TVar 2) (TVar 4)) (TFun (TNum) (TVar 5)))
 (Cnst (TFun (TVar 1) (TVar 5)) (TFun (TNum) (TVar 6)))))
(reset)
(test (typeof (app (fun 'x (id 'x)) (num 3)) (mtTEnv)) (list (TVar 2) (Cnst (TFun (TVar 1) (TVar 1)) (TFun (TNum) (TVar 2)))))
(reset)
(test/exn (typeof (id 'x) (mtTEnv)) "Exception: Identificador libre = x")
(reset)
(test (typeof (if0 (num 2) (num 5) (num 3)) (mtTEnv)) (list (TNum) (Cnst (TNum) (TNum)) (Cnst (TNum) (TNum))))

(printf "---------- Test (substitute) ----------\n\n")

(test (substitute (TVar 1) (TNum) '()) '())
(test (substitute (TVar 1) (TNum) (list (Cnst (TNum) (TNum)) (Cnst (TVar 1) (TNum)))) (list (Cnst (TNum) (TNum)) (Cnst (TNum) (TNum))))
(test (substitute (TVar 5) (TNum) (list (Cnst (TFun (TVar 1) (TFun (TVar 5) (TVar 3))) (TFun (TVar 1) (TNum))))) 
    (list (Cnst (TFun (TVar 1) (TFun (TNum) (TVar 3))) (TFun (TVar 1) (TNum)))))
(test (substitute (TVar 1) (TNum) (list (Cnst (TFun (TVar 1) (TVar 1)) (TFun (TNum) (TVar 2))))) (list (Cnst (TFun (TNum) (TNum)) (TFun (TNum) (TVar 2)))))

(printf "---------- Test (unify) ----------\n\n")

(test (unify '()) '())
(test (unify (list (Cnst (TNum) (TNum)) (Cnst (TVar 2) (TNum)))) (list (Cnst (TVar 2) (TNum))))
(test (unify (list (Cnst (TNum) (TNum)) (Cnst (TNum) (TNum)) (Cnst (TNum) (TNum)))) '())
(test (unify (list (Cnst (TVar 2) (TFun (TNum) (TVar 3))) (Cnst (TFun (TVar 1) (TVar 4)) (TVar 2))))
      (list (Cnst (TVar 4) (TVar 3)) (Cnst (TVar 1) (TNum)) (Cnst (TVar 2) (TFun (TNum) (TVar 3)))))
(test/exn (unify (list (Cnst (TNum) (TNum)) (Cnst (TNum) (TNum)) (Cnst (TVar 1) (TFun (TVar 1) (TFun (TVar 1) (TVar 2)))))) 
      "Exception: Error de Tipo: No se puede unificar [(TVar 1)] con [(TFun (TVar 1) (TFun (TVar 1) (TVar 2)))]")

(printf "---------- Test (lookup-list) ----------\n\n")

(test (lookup-list '() (TNum)) (TNum))
(test (lookup-list (list (Cnst (TVar 1) (TNum)) (Cnst (TVar 2) (TNum)) (Cnst (TNum) (TNum))) (TVar 2)) (TNum))
(test (lookup-list (list (Cnst (TVar 1) (TFun (TNum) (TVar 2))) (Cnst (TVar 2) (TNum))) (TVar 1)) (TFun (TNum) (TNum)))

(printf "---------- Test (runType) ----------\n\n")

(printf "***Ejemplos Enunciado***\n\n")
(test (runType '(fun (x) (+ x 1))) (TFun (TNum) (TNum)))
(reset)
(test (runType '(fun (x) x)) (TFun (TVar 1) (TVar 1)))
(reset)
(test (runType '(fun (x) 3)) (TFun (TVar 1) (TNum)))
(reset)
(test/exn (runType 'x) "Exception: Identificador libre = x")
(reset)
(test/exn (runType '((fun (x) (+ x 1)) (fun (x) x)))
          "Exception: Error de Tipo: No se puede unificar [num] con [(TFun (TVar 2) (TVar 2))]")

(printf "***Tests Adicionales***\n\n")
(test (runType '{- 3 {- {+ 50 {- 4 2}} 6}}) (TNum))
(test (runType '{with {y 20} {- 40 y}}) (TNum))
(reset)
(test/exn (runType '(with (x (+ 10 5)) (fun (y) (+ x (+ y z))))) "Exception: Identificador libre = z")
(reset)
(test (runType '((fun (x) (- 100 (+ x 25))) ((fun (t) (+ t t)) ((fun (y) (- (+ 7 5) y)) 2)))) (TNum))
(reset)
